# Generated by Django 5.2.7 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parent_posted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='parent',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
