# Generated by Django 5.2.7 on 2025-10-02 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_parent_options_alter_parent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
